% Run the fast CSOMA replication checks.
%
% The Bayesian HIV and high-dimensional examples can be computationally
% expensive. They are included in examples/ and can be run separately.

root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
acceptance_tol = 1e-10;

fprintf('Acceptance policy: fixed-seed workflows must satisfy the documented\n');
fprintf('finite-value, feasibility, and problem-specific diagnostic checks.\n');
fprintf('Exact cross-release or cross-platform equality is not required.\n\n');

fprintf('Running CSOMA smoke test...\n');
run(fullfile(root, 'examples', 'basic', 'run_basic.m'));
assert(isfinite(best_value) && all(isfinite(best_x)) && all(isfinite(history)), ...
    'csoma:replication:BasicFinite', ...
    'Basic workflow returned a non-finite value.');
assert(all(best_x >= lb - acceptance_tol) && all(best_x <= ub + acceptance_tol), ...
    'csoma:replication:BasicBounds', ...
    'Basic workflow returned a point outside the supplied bounds.');
assert(all(diff(history) <= acceptance_tol), ...
    'csoma:replication:BasicHistory', ...
    'Basic workflow best-so-far history worsened beyond tolerance.');
fprintf('PASS: finite bounded result and non-increasing best-so-far history.\n');

fprintf('\nRunning logistic-design example...\n');
run(fullfile(root, 'examples', 'logistic_design', 'run_logistic_design.m'));
logistic_weights = opt_design(2*k+1:3*k);
assert(isfinite(criterion_val) && criterion_val < 1e8, ...
    'csoma:replication:LogisticCriterion', ...
    'Logistic-design workflow returned a non-finite or penalty criterion.');
assert(all(opt_design(1:2*k) >= -1 - acceptance_tol) ...
    && all(opt_design(1:2*k) <= 1 + acceptance_tol) ...
    && all(logistic_weights >= -acceptance_tol) ...
    && abs(sum(logistic_weights) - 1) <= acceptance_tol, ...
    'csoma:replication:LogisticFeasibility', ...
    'Logistic-design support points or normalized weights are infeasible.');
diagnostic_grid = linspace(-1, 1, 201);
max_centered_sensitivity = -Inf;
for grid_i = 1:numel(diagnostic_grid)
    for grid_j = 1:numel(diagnostic_grid)
        current_sensitivity = sen_fun(diagnostic_grid(grid_i), diagnostic_grid(grid_j));
        max_centered_sensitivity = max(max_centered_sensitivity, current_sensitivity);
    end
end
assert(isfinite(max_centered_sensitivity) && max_centered_sensitivity <= 0.3, ...
    'csoma:replication:LogisticSensitivity', ...
    'Maximum centered sensitivity %.6g exceeds the 0.3 fast-check bound.', ...
    max_centered_sensitivity);
fprintf('PASS: feasible normalized design; 201-by-201 grid maximum %.6g <= 0.3.\n', ...
    max_centered_sensitivity);

fprintf('\nRunning Gaussian copula design example...\n');
run(fullfile(root, 'examples', 'copula_design', 'run_copula_design.m'));
assert(isfinite(criterion_val) && criterion_val < 1e8, ...
    'csoma:replication:CopulaDesignCriterion', ...
    'Copula-design workflow returned a non-finite or penalty criterion.');
assert(all(support >= -1 - acceptance_tol) && all(support <= 1 + acceptance_tol) ...
    && all(weights >= -acceptance_tol) ...
    && abs(sum(weights) - 1) <= acceptance_tol, ...
    'csoma:replication:CopulaDesignFeasibility', ...
    'Copula-design support points or normalized weights are infeasible.');
fprintf('PASS: finite non-penalty criterion, bounded support, normalized weights.\n');

fprintf('\nRunning Gaussian copula MLE example...\n');
run(fullfile(root, 'examples', 'copula_design', 'run_copula_mle.m'));
assert(isfinite(neg_loglik) && isfinite(rho_hat) && abs(rho_hat) < 1, ...
    'csoma:replication:CopulaMLEFinite', ...
    'Copula-MLE workflow returned an invalid likelihood or correlation.');
assert(abs(rho_hat - rho_true) <= 0.15, ...
    'csoma:replication:CopulaMLEAccuracy', ...
    'Estimated correlation differs from the seeded truth by more than 0.15.');
fprintf('PASS: finite objective and |estimated rho - true rho| = %.6g <= 0.15.\n', ...
    abs(rho_hat - rho_true));

fprintf('\nRunning Wasserstein regression example...\n');
run(fullfile(root, 'examples', 'wasserstein_regression', 'run_wasserstein_regression.m'));
assert(isfinite(loss_value) && all(isfinite(theta_hat)), ...
    'csoma:replication:WassersteinFinite', ...
    'Wasserstein-regression workflow returned non-finite output.');
assert(loss_value <= 0.02 && max(abs(theta_hat - theta_true)) <= 0.35, ...
    'csoma:replication:WassersteinAccuracy', ...
    ['Wasserstein-regression output exceeds the acceptance bounds: ' ...
     'loss <= 0.02 and maximum coefficient error <= 0.35.']);
fprintf('PASS: loss %.6g <= 0.02; maximum coefficient error %.6g <= 0.35.\n', ...
    loss_value, max(abs(theta_hat - theta_true)));

fprintf('\nRunning Riemannian sphere design example...\n');
run(fullfile(root, 'examples', 'riemannian_design', 'run_riemannian_sphere_design.m'));
point_norm_error = max(abs(sqrt(sum(points.^2, 2)) - 1));
assert(isfinite(criterion_value) && criterion_value < 1e8, ...
    'csoma:replication:RiemannianCriterion', ...
    'Riemannian-design workflow returned a non-finite or penalty criterion.');
assert(all(weights >= -acceptance_tol) ...
    && abs(sum(weights) - 1) <= acceptance_tol ...
    && point_norm_error <= acceptance_tol, ...
    'csoma:replication:RiemannianFeasibility', ...
    'Riemannian-design points or normalized weights are infeasible.');
fprintf('PASS: finite non-penalty criterion, unit-sphere points, normalized weights.\n');

fprintf('\nRunning TSP example...\n');
run(fullfile(root, 'examples', 'tsp', 'run_tsp.m'));
assert(isfinite(min_route_length) && isequal(sort(min_route_idx(:))', 1:n), ...
    'csoma:replication:TSPRoute', ...
    'TSP workflow did not return a finite valid permutation of all cities.');
recomputed_route_length = 0;
for route_i = 1:n-1
    recomputed_route_length = recomputed_route_length ...
        + DM(min_route_idx(route_i), min_route_idx(route_i + 1));
end
recomputed_route_length = recomputed_route_length ...
    + DM(min_route_idx(end), min_route_idx(1));
route_tol = acceptance_tol * max(1, abs(min_route_length));
assert(abs(recomputed_route_length - min_route_length) <= route_tol, ...
    'csoma:replication:TSPDistance', ...
    'Reported TSP route length does not match the returned route.');
fprintf('PASS: valid 10-city permutation and independently recomputed route length.\n');

fprintf('\nAll fast replication acceptance checks passed.\n');
